### ISSUE TITLE
Music not playing

### ISSUE THREAD

**Issue by boingfromdiscord** [WarHammer414/erela.js#21]
I tried to play music but it's just not playing I console logged around the bot joins channel sends queue message adds the song to playlist it just is not playing anything

**Comment by Anish-Shobith** [comment]
We need ***your code*** in order to reproduce this issue you have posted here , this seems like you could be helped on discord ? if they tried they might have missed out something. post the full code and we will see if we are able to reproduce this issue if we are not able to , then mostly there is something wrong on your end or the code you are trying probably has some problem

**Comment by SerenModz21** [comment]
make sure erela and lavallink is up to date as well

**Comment by Anish-Shobith** [comment]
There seem to be no response , closing this issue , if the issue continues and its not a issue on your end reopen the issue but as the release of v2 it should work.
